### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MrCodecat** [GamerKing195/AutoUpdaterAPI#1]
[14:12:42 INFO]: _MrCodecat_ issued server command: /update 33379 PotionsGUI
[14:12:43 ERROR]: [AutoUpdaterAPI] A severe error has occurred with AutoUpdaterAPI.
[14:12:43 ERROR]: [AutoUpdaterAPI] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/PluginUpdater/issues.
[14:12:43 ERROR]: [AutoUpdaterAPI]
[14:12:43 ERROR]: [AutoUpdaterAPI] ============== BEGIN ERROR ==============
[14:12:43 ERROR]: [AutoUpdaterAPI] PLUGIN VERSION: AutoUpdaterAPI V2.0.1
[14:12:43 ERROR]: [AutoUpdaterAPI]
[14:12:43 ERROR]: [AutoUpdaterAPI] PLUGIN MESSAGE: Error occurred while updating PotionsGUI.
[14:12:43 ERROR]: [AutoUpdaterAPI]
[14:12:43 ERROR]: [AutoUpdaterAPI] MESSAGE: String index out of range: -1
[14:12:43 ERROR]: [AutoUpdaterAPI]
[14:12:43 ERROR]: [AutoUpdaterAPI] STACKTRACE:
[14:12:43 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[14:12:43 WARN]:        at java.lang.String.substring(Unknown Source)
[14:12:43 WARN]:        at com.gamerking195.dev.autoupdaterapi.Updater$2.run(SourceFile:110)
[14:12:43 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:12:43 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:12:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:12:43 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:12:43 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:12:43 ERROR]: [AutoUpdaterAPI]
[14:12:43 ERROR]: [AutoUpdaterAPI] ============== END ERROR ==============

**Comment by cadenkriese** [comment]
Hello, sorry for my delay, github notifcations were off for me for some reason, I'll look into this as soon as possible. If you could please provide any relevant details, such as API usage code, and what stage of the update this happened in it would be much appreciated.

**Comment by MrCodecat** [comment]
So here is my code:
`public class CommandEx implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if(sender instanceof Player){
        if(args.length > 1 && NumberUtils.isNumber(args[0])) {
            UpdateLocale locale = new UpdateLocale();
           locale.setFileName(args[1]);
           locale.setPluginName(args[1]);
           new Updater((Player) sender, test.instance,Integer.valueOf(args[0]),locale,false,false).update();
        }
        }
        return false;
    }
}`

**Comment by cadenkriese** [comment]
Does this happen every time you attempt to run it? Please turn on debug mode with AutoUpdaterAPI.setDebug(true); and send me the full log (apologies this takes a lot to fix, I believe it's an issue with one of my obfuscated files.
