### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Misio12320** [GamerKing195/AutoUpdaterAPI#4]
[AutoUpdaterAPI] A severe error has occurred with AutoUpdaterAPI.
[16:58:50 ERROR]: [AutoUpdaterAPI] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/fl0gic/AutoUpdaterAPI/issues.
[16:58:50 ERROR]: [AutoUpdaterAPI]
[16:58:50 ERROR]: [AutoUpdaterAPI] ============== BEGIN ERROR ==============
[16:58:50 ERROR]: [AutoUpdaterAPI] PLUGIN VERSION: AutoUpdaterAPI V2.5.3-SNAPSHOT
[16:58:50 ERROR]: [AutoUpdaterAPI]
[16:58:50 ERROR]: [AutoUpdaterAPI] PLUGIN MESSAGE: Error occurred while initializing CommandSigns.
[16:58:50 ERROR]: [AutoUpdaterAPI]
[16:58:50 ERROR]: [AutoUpdaterAPI] MESSAGE: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[16:58:50 ERROR]: [AutoUpdaterAPI]
[16:58:50 ERROR]: [AutoUpdaterAPI] STACKTRACE:
[16:58:50 WARN]: org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[16:58:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:77)
[16:58:50 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[16:58:50 WARN]: at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(SourceFile:192)
[16:58:50 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[16:58:50 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[16:58:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[16:58:50 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[16:58:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[16:58:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[16:58:50 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:58:50 WARN]: Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[16:58:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:161)
[16:58:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:75)
[16:58:50 WARN]: ... 9 more
[16:58:50 WARN]: Caused by: java.util.zip.ZipException: error in opening zip file
[16:58:50 WARN]: at java.util.zip.ZipFile.open(Native Method)
[16:58:50 WARN]: at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[16:58:50 WARN]: at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[16:58:50 WARN]: at java.util.jar.JarFile.<init>(JarFile.java:166)
[16:58:50 WARN]: at java.util.jar.JarFile.<init>(JarFile.java:130)
[16:58:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:149)
[16:58:50 WARN]: ... 10 more
[16:58:50 ERROR]: [AutoUpdaterAPI]
[16:58:50 ERROR]: [AutoUpdaterAPI] ============== END ERROR ==============
[16:58:50 INFO]: [CommandSigns] Enabling CommandSigns v1.8*
[16:58:50 WARN]: [AutoUpdaterAPI] Task #61928 for AutoUpdaterAPI v2.5.3-SNAPSHOT generated an exception
java.lang.NoSuchFieldError: BLOCK_NOTE_BASS
at com.gamerking195.dev.up2date.ui.UpdateGUI.lambda$updatePlugin$15(UpdateGUI.java:657) ~[?:?]
at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(SourceFile:211) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by cadenkriese** [comment]
Hey there, thanks for the report! Would you mind testing the latest snapshot version (2.5.4-SNAPSHOT) of AutoUpdaterAPI for me? You can download it [here](https://ci.gamerking195.com/job/AutoUpdaterAPI/lastSuccessfulBuild/artifact/target/AutoUpdaterAPI.jar). The new version should add support for Spigot 1.13.2, but I haven't had a chance to thoroughly test it yet.

**Comment by Misio12320** [comment]
[09:26:24 INFO]: [KInvBackup] Disabling KInvBackup v1.3
[09:26:26 ERROR]: [AutoUpdaterAPI] A severe error has occurred with AutoUpdaterAPI.
[09:26:26 ERROR]: [AutoUpdaterAPI] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/fl0gic/AutoUpdaterAPI/issues.
[09:26:26 ERROR]: [AutoUpdaterAPI]
[09:26:26 ERROR]: [AutoUpdaterAPI] ============== BEGIN ERROR ==============
[09:26:26 ERROR]: [AutoUpdaterAPI] PLUGIN VERSION: AutoUpdaterAPI V2.5.3-SNAPSHOT
[09:26:26 ERROR]: [AutoUpdaterAPI]
[09:26:26 ERROR]: [AutoUpdaterAPI] PLUGIN MESSAGE: Error occurred while initializing KInvBackup.
[09:26:26 ERROR]: [AutoUpdaterAPI]
[09:26:26 ERROR]: [AutoUpdaterAPI] MESSAGE: java.lang.IllegalStateException: zip file closed
[09:26:26 ERROR]: [AutoUpdaterAPI]
[09:26:26 ERROR]: [AutoUpdaterAPI] STACKTRACE:
[09:26:26 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[09:26:26 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[09:26:26 WARN]: at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(Updater.java:196)
[09:26:26 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:26:26 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[09:26:26 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:26:26 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[09:26:26 WARN]: at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[09:26:26 WARN]: at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[09:26:26 WARN]: at java.util.jar.JarFile.getEntry(JarFile.java:240)
[09:26:26 WARN]: at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[09:26:26 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:26:26 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:26:26 WARN]: at java.lang.Class.forName0(Native Method)
[09:26:26 WARN]: at java.lang.Class.forName(Class.java:348)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62)
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[09:26:26 WARN]: ... 9 more
[09:26:26 ERROR]: [AutoUpdaterAPI]
[09:26:26 ERROR]: [AutoUpdaterAPI] ============== END ERROR ==============
[09:26:26 INFO]: A severe error has occurred with the Up2Date plugin.
[09:26:26 INFO]: If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/Up2Date/issues.
[09:26:26 INFO]: Or on spigot at https://spigotmc.org/threads/284883/
[09:26:26 ERROR]: [U2D]
[09:26:26 ERROR]: [U2D] ============== BEGIN ERROR ==============
[09:26:26 ERROR]: [U2D] PLUGIN VERSION: V1.5.3 (LATEST)
[09:26:26 ERROR]: [U2D]
[09:26:26 ERROR]: [U2D] PLUGIN MESSAGE: Error occurred while fixing failed plugin download.
[09:26:26 ERROR]: [U2D]
[09:26:26 ERROR]: [U2D] MESSAGE: java.lang.IllegalStateException: zip file closed
[09:26:26 ERROR]: [U2D]
[09:26:26 ERROR]: [U2D] STACKTRACE:
[09:26:26 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[09:26:26 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[09:26:26 WARN]: at com.gamerking195.dev.up2date.ui.UpdateGUI.restoreFile(UpdateGUI.java:819)
[09:26:26 WARN]: at com.gamerking195.dev.up2date.ui.UpdateGUI.lambda$updatePlugin$15(UpdateGUI.java:654)
[09:26:26 WARN]: at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(Updater.java:215)
[09:26:26 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:26:26 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[09:26:26 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[09:26:26 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:26:26 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[09:26:26 WARN]: at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[09:26:26 WARN]: at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[09:26:26 WARN]: at java.util.jar.JarFile.getEntry(JarFile.java:240)
[09:26:26 WARN]: at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[09:26:26 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:26:26 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:26:26 WARN]: at java.lang.Class.forName0(Native Method)
[09:26:26 WARN]: at java.lang.Class.forName(Class.java:348)
[09:26:26 WARN]: at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62)
[09:26:26 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[09:26:26 WARN]: ... 11 more
[09:26:26 ERROR]: [U2D]
[09:26:26 ERROR]: [U2D] ============== END ERROR ==============
[09:26:27 INFO]: [CommandSigns] Disabling CommandSigns v1.8
[09:26:28 ERROR]: [AutoUpdaterAPI] A severe error has occurred with AutoUpdaterAPI.
[09:26:28 ERROR]: [AutoUpdaterAPI] If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/fl0gic/AutoUpdaterAPI/issues.
[09:26:28 ERROR]: [AutoUpdaterAPI]
[09:26:28 ERROR]: [AutoUpdaterAPI] ============== BEGIN ERROR ==============
[09:26:28 ERROR]: [AutoUpdaterAPI] PLUGIN VERSION: AutoUpdaterAPI V2.5.3-SNAPSHOT
[09:26:28 ERROR]: [AutoUpdaterAPI]
[09:26:28 ERROR]: [AutoUpdaterAPI] PLUGIN MESSAGE: Error occurred while initializing CommandSigns.
[09:26:28 ERROR]: [AutoUpdaterAPI]
[09:26:28 ERROR]: [AutoUpdaterAPI] MESSAGE: java.lang.IllegalStateException: zip file closed
[09:26:28 ERROR]: [AutoUpdaterAPI]
[09:26:28 ERROR]: [AutoUpdaterAPI] STACKTRACE:
[09:26:28 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[09:26:28 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[09:26:28 WARN]: at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(Updater.java:196)
[09:26:28 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:26:28 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[09:26:28 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:26:28 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[09:26:28 WARN]: at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[09:26:28 WARN]: at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[09:26:28 WARN]: at java.util.jar.JarFile.getEntry(JarFile.java:240)
[09:26:28 WARN]: at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[09:26:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:26:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:26:28 WARN]: at java.lang.Class.forName0(Native Method)
[09:26:28 WARN]: at java.lang.Class.forName(Class.java:348)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62)
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[09:26:28 WARN]: ... 9 more
[09:26:28 ERROR]: [AutoUpdaterAPI]
[09:26:28 ERROR]: [AutoUpdaterAPI] ============== END ERROR ==============
[09:26:28 INFO]: A severe error has occurred with the Up2Date plugin.
[09:26:28 INFO]: If you cannot figure out this error on your own (e.g. a config error) please copy and paste everything from here to END ERROR and post it at https://github.com/GamerKing195/Up2Date/issues.
[09:26:28 INFO]: Or on spigot at https://spigotmc.org/threads/284883/
[09:26:28 ERROR]: [U2D]
[09:26:28 ERROR]: [U2D] ============== BEGIN ERROR ==============
[09:26:28 ERROR]: [U2D] PLUGIN VERSION: V1.5.3 (LATEST)
[09:26:28 ERROR]: [U2D]
[09:26:28 ERROR]: [U2D] PLUGIN MESSAGE: Error occurred while fixing failed plugin download.
[09:26:28 ERROR]: [U2D]
[09:26:28 ERROR]: [U2D] MESSAGE: java.lang.IllegalStateException: zip file closed
[09:26:28 ERROR]: [U2D]
[09:26:28 ERROR]: [U2D] STACKTRACE:
[09:26:28 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[09:26:28 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[09:26:28 WARN]: at com.gamerking195.dev.up2date.ui.UpdateGUI.restoreFile(UpdateGUI.java:819)
[09:26:28 WARN]: at com.gamerking195.dev.up2date.ui.UpdateGUI.lambda$updatePlugin$15(UpdateGUI.java:654)
[09:26:28 WARN]: at com.gamerking195.dev.autoupdaterapi.Updater$1$1.run(Updater.java:215)
[09:26:28 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:26:28 WARN]: at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[09:26:28 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[09:26:28 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:26:28 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[09:26:28 WARN]: at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[09:26:28 WARN]: at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[09:26:28 WARN]: at java.util.jar.JarFile.getEntry(JarFile.java:240)
[09:26:28 WARN]: at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:192)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84)
[09:26:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:26:28 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:26:28 WARN]: at java.lang.Class.forName0(Native Method)
[09:26:28 WARN]: at java.lang.Class.forName(Class.java:348)
[09:26:28 WARN]: at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62)
[09:26:28 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[09:26:28 WARN]: ... 11 more
[09:26:28 ERROR]: [U2D]
[09:26:28 ERROR]: [U2D] ============== END ERROR ==============
[09:26:29 WARN]: [U2D] Task #923027 for Up2Date v1.5.3 generated an exception
java.lang.NoSuchFieldError: BLOCK_NOTE_BASS
at com.gamerking195.dev.up2date.ui.UpdateGUI$6.run(UpdateGUI.java:743) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:26:31 WARN]: [U2D] Task #923027 for Up2Date v1.5.3 generated an exception
java.lang.NoSuchFieldError: BLOCK_NOTE_BASS
at com.gamerking195.dev.up2date.ui.UpdateGUI$6.run(UpdateGUI.java:743) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:26:33 WARN]: [U2D] Task #923027 for Up2Date v1.5.3 generated an exception
java.lang.NoSuchFieldError: BLOCK_NOTE_BASS
at com.gamerking195.dev.up2date.ui.UpdateGUI$6.run(UpdateGUI.java:743) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-564]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-564]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[09:26:35 WARN]: [U2D] Task #923027 for Up2Date v1.5.3 generated an exception

**Comment by cadenkriese** [comment]
I'm currently working on a major update for AutoUpdater, on the V3 branch. Once version 3 is released, if you continue to experience these errors, please reopen this issue; until then, I'll be closing it.
