### ISSUE TITLE
Invalid plugin.yml in dev build #84

### ISSUE THREAD

**Issue by axemwa** [GamerKing195/AutoUpdaterAPI#6]
[17:38:00 ERROR]: Could not load 'plugins\AutoUpdaterAPI.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.13.2.jar:git-Paper-648]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:140) ~[patched_1.13.2.jar:git-Paper-648]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-648]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-648]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-648]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by cadenkriese** [comment]
This build was a beta version of AutoUpdater I'm working on, in the future note that the (origin/v3) on the build name means it is a heavy beta version and could be fully broken. Builds from origin/master will typically be more stable, but the latest Spigot version is always the most stable version.
